development:
  adapter: postgresql
  encoding: unicode
  database: pickemup_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pickemup_dev
  pool: 5
  host: localhost