production:
  adapter: postgresql
  encoding: unicode
  database: pickemup_prod
  pool: 5
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  database: pickemup_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pickemup_test
  pool: 5
  host: localhost